# Generated by Django 5.2 on 2026-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_link_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
