# Generated by Django 5.2 on 2026-03-31 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramnotification',
            name='transaction_sent_dd9786_idx',
        ),
        migrations.AddField(
            model_name='telegramnotification',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramnotification',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='telegramnotification',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['sent', 'failed'], name='transaction_sent_d4e62d_idx'),
        ),
    ]
