# Generated by Django 5.2 on 2026-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_telegramnotification_transaction_sent_dd9786_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotification',
            name='processing_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
