# Generated by Django 5.2 on 2026-06-18 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_backfill_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_clp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('CLP', 'CLP'), ('USD', 'USD')], default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_status',
            field=models.CharField(choices=[('na', 'N/A'), ('estimated', 'Estimado'), ('final', 'Final')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settles', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('ingreso', 'Ingreso'), ('comision', 'Comisión/Cargos'), ('pago_tarjeta', 'Pago tarjeta'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
