# Generated by Django 5.2 on 2026-06-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_backfill_amount_clp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debito', 'Débito'), ('giro', 'Giro'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('ingreso', 'Ingreso'), ('comision', 'Comisión/Cargos'), ('pago_tarjeta', 'Pago tarjeta'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
